board/urls.py
from django.urls import path
from . import views
from board.views import CreateGameView
app_name = 'board'
urlpatterns = [
    path("", CreateGameView.as_view(), name = "index")
]

exposingcovids/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls', namespace='board')),
    path('', include("loading.urls"))
]

loading/urls.py
from django.urls import path
from . import views
from loading.views import LoadGameView

app_name = 'loading'
urlpatterns = [
    path("", LoadGameView.as_view(), name = "index"),
    path("start", LoadGameView.as_view(), name = "start")
]

board/models.py
from django.db import models
import random
import sys

class Card:

    def __init__(self,value=0,played=False):
        #Default constructor
        self.value = value
        self.played = played

    def getValue(self):
        return self.value

class InfluentialFigureCard(Card):
    def __init__(self,value=0,played=False):
        super().__init__(value,played)

class SuperspreaderEventCard(Card):
    def __init__(self,value=0,played=False):
        super().__init__(value,played)

class Deck:
    cardTypes = {"covid exposure":4,"mask/ppe":6,"stay at home":5,
    "quarantine":4, "stimulus check":4,"event cancellation":4,"covid forecast":5,}
    influentialFigureCards = {"trump":4,"fauci":4, "NFL":4,"pfizer":4,"zoom":4}
    superspreaderCards = {"football game":1,"cruise":1,"birthday party":1,"concert":1}
    def __init__(self):
        self.cards = []
        for key in self.cardTypes:
            for numCards in range(self.cardTypes[key]):
                card = Card(key,False)
                self.cards.append(card)
        
        for key in self.influentialFigureCards:
            for numCards in range(self.influentialFigureCards[key]):
                card = InfluentialFigureCard(key,False)
                self.cards.append(card)
        
        for key in self.superspreaderCards:
            for numCards in range(self.superspreaderCards[key]):
                card = SuperspreaderEventCard(key,False)
                self.cards.append(card)
        self.shuffle()

    def add_card(self,card):
        self.cards.append(card)

    def remove_card(self,i=0):
        return self.cards.pop(i)

    def shuffle(self):
        random.shuffle(self.cards)
    
    #get properties of the deck
    def getDeckLength(self):
        return len(self.cards)
    
    def getCard(self,index):
        return self.cards[index]

    def listDeck(self):
        deckList = []
        for card in self.cards:
            deckList.append(card.getValue())
        return(deckList)

#can make this take a parameter of player
class Hand(Deck):
    def __init__(self):
        self.cards = []

    def add_card(self,card):
        self.cards.append(card)

    def remove_card(self,i=0):
        return self.cards.pop(i)

    def getCards(self):
        handList = []
        for card in self.cards:
            handList.append(card.getValue())
        return(handList)

class DiscardPile(Deck):
    def __init__(self):
        self.cards = []
    
    def add_card(self,card):
        self.cards.append(card)

    def remove_card(self,i=0):
        return self.cards.pop(i)

    def getDiscardDeckLength(self):
        return len(self.cards)

    def getCards(self):
        discardList = []
        for card in self.cards:
            discardList.append(card.getValue())
        return(discardList)
    

class Player:
    def __init__(self,turn,hand,name=''):
        self.hand = hand
        self.name = name
        self.turn = turn

    def is_player_turn(self):
        return self.turn

    def getName(self):
        return self.name
    
    def getHand(self):
        return self.hand

loading/models.py
from django.db import models

# Create your models here.

board/views.py
from django.http import HttpResponse
from django.shortcuts import render
from board.models import Deck
from board.models import Hand
from board.models import Player
from board.models import DiscardPile
from django.views.generic import View

class CreateGameView(View):
    #template_name = 'board/index.html'
    def get(self,request,*args, **kwargs):
        players = []
        deck = Deck()
        discardPile = DiscardPile()
        names = request.session.get('names')
        count = 0
        for name in names:
            if(count == 0):
                turn = True
            else:
                turn = False
            hand = Hand()
            for i in range(7):
                hand.add_card(deck.remove_card())
            player = Player(turn,name,hand)
            #for now, just send data as a list
            players.append([turn,name,hand.getCards()])
        
        deckLen = deck.getDeckLength()
        deckList = deck.listDeck()
        return render(request,'board/index.html',{
            "deckLen":deckLen,
            "deckList":deckList,
            "players":players
        })

loading/views.py
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django import forms
from board.models import Player
from django.views.generic import View

class NewTaskForm(forms.Form):
    name = forms.CharField(label = "Player Name")

class LoadGameView(View):
    def get(self,request,*args, **kwargs):
        #saves past sessions (past names created)
        #comment out the line below to refresh the names list
        if "names" not in request.session:
            request.session["names"] = []
        return render(request,'loading/index.html',{
            "names":request.session["names"],
            "form": NewTaskForm()
        })

    def post(self,request,*args, **kwargs):
        if request.method == "POST":
            form = NewTaskForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data["name"]
            request.session["names"] += [name]
        else:
            return render(request, 'loading/index.html',{
                "form": form,
                "names":request.session["names"]
            })
        return render(request,'loading/start.html',{
            "form": NewTaskForm(),
            "names":request.session["names"]
        })
            

board/templates/board/index.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Main Board Page</title>
        <link href="{% static 'board/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h3>Cards in Deck: {{ deckLen }}</h3>
        <ul>
            {% for card in deckList %}
                <li>{{ card }}</li>
            {% endfor %}
        </ul>
        {% for player in players %}
            <p>Name: {{ player.1 }}</p>
            {% for handCard in player.2 %}
                <li>{{ handCard }}</li>
            {% endfor %}
        {% endfor %}
    </body>
</html>

loading/templates/loading/index.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Loading Page: Add Players</title>
        <link href="{% static 'loading/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2>Add Players</h2>
        <form action = "{% url 'loading:index' %}" method = "post">
            {% csrf_token %}
            {{ form }}
            <input type = "submit" />
        </form>
    </body>
</html>

loading/templates/loading/start.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
    <head>
        <title>Loading Page: Start</title>
        <link href="{% static 'loading/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h2>Loading Page</h2>
        <h2>Players:</h2>
        <ul>
            {% for name in names %}
                <li>{{ name }}</li>
            {% endfor %}
        </ul>
        <div class="btn-box">
            <a href="{% url 'board:index' %}">
                <p class="btn-text">Start Game</p>
            </a>
        </div>
    </body>
</html>